[dependencies]
anyhow = "1.0.98"
atom_syndication = "0.12.7"
chrono = {version = "0.4.41", default-features = false, features = ["serde"]}
rss = "2.0.12"
serde = {version = "1.0.219", features = ["serde_derive"]}
serde_json = "1.0.140"
ureq = {version = "3.0.12", features = ["charset"]}
url = { version = "2.5.4", default-features = false, features = ["std", "serde"] }

[package]
name = "r"
version = "0.1.0"
edition = "2024"
