[dependencies]
anyhow = "1.0.98"
atom_syndication = "0.12.7"
chrono = {version = "0.4.41", default-features = false, features = ["serde"]}
futures-lite = "2.6.0"
html2md = "0.2.15"
quick-xml = {version = "0.37.5", features = ["encoding"]}
readability = {version = "0.3.0", default-features = false}
rss = "2.0.12"
serde = {version = "1.0.219", features = ["serde_derive"]}
serde_json = "1.0.140"
smol = "2.0.2"
ureq = {version = "3.0.12", features = ["charset"]}
url = { version = "2.5.4", default-features = false, features = ["std", "serde"] }
url_serde = "0.2.0"

[package]
name = "r"
version = "0.1.0"
edition = "2024"
