[package]
name = "r"
version = "0.1.0"
edition = "2024"

[dependencies]
atom_syndication = "0.12.7"
quick-xml = { version = "0.37.5", default-features = false, features = ["encoding"] }
rss = "2.0.12"
ureq = { version = "3.0.12", features = ["charset"] }
